### ISSUE TITLE
Cannot find module 'egoroof-blowfish'

### ISSUE THREAD

**Issue by churti** [egoroof/blowfish#4]
I need help. 
I have tried everything on stackoverflow but nothing helps. 
i followed ur installation guide but after building my app:
`Error: Cannot find module 'egoroof-blowfish'
at Function.Module._resolveFilename (module.js:513:15)
at Function.Module._load (module.js:458:25)
at Module.require (module.js:541:17)
at require (internal/module.js:11:18)
at self.require (<anonymous>:11:26)`
this occurs in the console.

**Comment by churti** [comment]
Ok nevermind ... found my problem :D
